# conda env create -f environment.yml -n idr-omero
name: torch
channels:
  - defaults
  - anaconda
  - pytorch
  - idr
  - ome
  - conda-forge
  - bioconda
dependencies:
  - idr-py
  - torchvision
  - tensorboard
  - pytorch
  - pytorch-lightning
  - matplotlib
  - pip 
  - pip:
    - nonechucks